FROM python:3.11-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY config.py .
COPY redirect/ redirect/
ENV PORT=8080
CMD uvicorn redirect.app:app --host 0.0.0.0 --port $PORT
