FROM python:3.11-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY config.py .
COPY monitor/ monitor/
COPY bot/ bot/
COPY migrations/ migrations/
CMD ["python", "-m", "bot.bot"]
